[package]
name = "benchmark"
version = "0.1.0"
edition = "2024"

[dependencies]
qdrant-client = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
clap = { workspace = true }
datafusion = "54.1"
futures = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1.24", features = ["v4"] }
rayon = "1.12"
reqwest = { version = "0.13", features = ["json"] }
